### ISSUE TITLE
Liscense

### ISSUE THREAD

**Issue by SkeletonPunk** [DasUmlaut/Olympia#20]
What is the license for this mod?

**Comment by RobMayer** [comment]
Beerware with the a Wil-Wheaton Law addendum

**Comment by SkeletonPunk** [comment]
XD ok.

**Comment by RobMayer** [comment]
Actually, one more stipulation: credit where credit is due. Bear in mind that the various texture packs have their own liscences (DokuCraft for example) and that can get very hairy. I'd check in DokuCraft's thread for information on that front.
